version: "3.9"
services:
  backend:
    build: .docker/backend
    image: node:t_backend
    volumes:
      - backend_modules:/src/backend/node_modules
      - ./backend:/src/backend
    ports:
      - 3000:3333
    command: bash -c "npm i && npm run dev"
  frontend:
    build: .docker/frontend
    image: node:t_frontend
    volumes:
      - frontend_modules:/src/frontend/node_modules
      - ./frontend:/src/frontend
    ports:
      - 3333:8080
    command: bash -c "npm i && npm run serve"
volumes:
  backend_modules:
  frontend_modules: