#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $DEV_USER LOGIN PASSWORD '$DEV_PASSWORD';
    CREATE DATABASE $DEV_DB ENCODING 'UTF8';
    GRANT ALL PRIVILEGES ON DATABASE $DEV_DB TO $DEV_USER;
EOSQL

psql -v ON_ERROR_STOP=1 -U "$DEV_USER" -W "$DEV_PASSWORD" -d "$DEV_DB" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL