#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $DEV_USER LOGIN PASSWORD '$DEV_PASSWORD';
    CREATE DATABASE $DEV_DB ENCODING 'UTF8';
    GRANT ALL PRIVILEGES ON DATABASE $DEV_DB TO $DEV_USER;
EOSQL